#!/usr/bin/env sh
##############################################################################
# Gradle start up script for POSIX generated by Gradle.
# If gradle-wrapper.jar is missing, Android Studio will offer to regenerate
# it automatically the first time you open/sync this project.
##############################################################################
DIR="$(cd "$(dirname "$0")" && pwd)"
exec "$DIR/gradle/wrapper/gradle-wrapper.jar" "$@" 2>/dev/null || \
  echo "Abre este proyecto con Android Studio: se generará el wrapper de Gradle automáticamente al sincronizar." 
